--CREATE TABLE CLIENT_MASTER(CLIENTNO VARCHAR(6) CHECK(CLIENTNO LIKE 'C%') PRIMARY KEY, NAME VARCHAR(20) NOT NULL,
--	ADDRESS1 VARCHAR(30), ADDRESS2 VARCHAR(30), CITY VARCHAR(15),PINCODE NUMERIC(8), STATE VARCHAR(15), BALDUE NUMERIC(10,2) );

----INSERT INTO CLIENT_MASTER(CLIENTNO, NAME, CITY, PINCODE, STATE, BALDUE)
----	VALUES('C00001','Ivan Bayross','Mumbai',400054,'Maharashtra',15000);

--SELECT * FROM CLIENT_MASTER;


--CREATE TABLE PRODUCT_MASTER(PRODUCTNO VARCHAR(6) CHECK(PRODUCTNO LIKE 'P%') PRIMARY KEY, DESCRIPTION VARCHAR(15) NOT NULL,
--	PROFITPERC NUMERIC(4,2) NOT NULL, UNITMEASURE VARCHAR(10) NOT NULL, QTYONHAND NUMERIC(8) NOT NULL, 
--	REORDERLVL NUMERIC(8) NOT NULL, SELLPRICE NUMERIC(8,2) NOT NULL, CONSTRAINT CHK1 CHECK(SELLPRICE <> 0),
--	COSTPRICE NUMERIC(8,2) NOT NULL, CONSTRAINT CHK2 CHECK(COSTPRICE <> 0));

--INSERT INTO PRODUCT_MASTER VALUES('P00001','T-Shirts',5,'Piece',200,50,350,250);

--SELECT * FROM PRODUCT_MASTER;


--CREATE TABLE SALESMAN_MASTER(SALESMANNO VARCHAR(6) CHECK(SALESMANNO LIKE 'S%') PRIMARY KEY, SALESMANNAME VARCHAR(20) NOT NULL,
--	ADDRESS1 VARCHAR(30) NOT NULL, ADDRESS2 VARCHAR(30), CITY VARCHAR(20), PINCODE NUMERIC(8),
--	STATE VARCHAR(20), SALAMT NUMERIC(8,2) NOT NULL, CONSTRAINT CHK3 CHECK(SALAMT <> 0), TGTTOGET NUMERIC(6,2),
--	YTDSALES NUMERIC(6,2) NOT NULL, REMARKS VARCHAR(60));

--INSERT INTO SALESMAN_MASTER VALUES('S00001','Aman','A/14','Worli','Mumbai',400002,'Maharashtra',3000,100,50,'Good');

--SELECT * FROM SALESMAN_MASTER;


--CREATE TABLE SALES_ORDER(ORDERNO VARCHAR(6) CHECK(ORDERNO LIKE 'O%') PRIMARY KEY, CLIENTNO VARCHAR(6), 
--	FOREIGN KEY(CLIENTNO) REFERENCES CLIENT_MASTER(CLIENTNO), ORDERDATE DATE, DELYADDR VARCHAR(25), 
--	SALESMANNO VARCHAR(6), FOREIGN KEY(SALESMANNO) REFERENCES SALESMAN_MASTER(SALESMANNO),
--	DELYTYPE CHAR(1),CONSTRAINT CHK4 CHECK(DELYTYPE='p' OR DELYTYPE='F'),
--	BILLEDYN CHAR(1),CONSTRAINT CHK5 CHECK(BILLEDYN='Y' OR BILLEDYN='N'),
--	DELYDATE DATE,
--	ORDERSTATUS VARCHAR(10), CONSTRAINT CHK6 CHECK(ORDERSTATUS='IN PROCESS' OR ORDERSTATUS='FULFILLED' 
--	OR ORDERSTATUS='BACK ORDER' OR ORDERSTATUS='CANCELLED'));


--INSERT INTO SALES_ORDER (ORDERNO, ORDERDATE,CLIENTNO,DELYTYPE,BILLEDYN,SALESMANNO,DELYDATE,ORDERSTATUS)
--	VALUES('O19001','12-june-02','C00001','F','N','S00001','20-july-02','In Process');

--SELECT * FROM SALES_ORDER;



--CREATE TABLE SALES_ORDER_DETAILS(ORDERNO VARCHAR(6), FOREIGN KEY(ORDERNO) REFERENCES SALES_ORDER(ORDERNO),
--	PRODUCTNO VARCHAR(6), FOREIGN KEY(PRODUCTNO) REFERENCES PRODUCT_MASTER(PRODUCTNO),
--	QTYORDERED NUMERIC(8), QTYDISP NUMERIC(8), PRODUCTRATE NUMERIC(10,2),
--	PRIMARY KEY(ORDERNO, PRODUCTNO));

--INSERT INTO SALES_ORDER_DETAILS(ORDERNO,PRODUCTNO,QTYORDERED,QTYDISP,PRODUCTRATE)
--	VALUES('O19001','P00001',4,4,525);

--SELECT * FROM SALES_ORDER_DETAILS;
 



 -- 1 --
 SELECT NAME FROM CLIENT_MASTER;

 -- 2 --
 SELECT NAME FROM CLIENT_MASTER WHERE CITY='Mumbai';

 -- 3 --
 SELECT DESCRIPTION FROM PRODUCT_MASTER WHERE SELLPRICE>2000 AND SELLPRICE<50000;

 -- 4 --
 SELECT NAME,CITY,STATE FROM CLIENT_MASTER WHERE STATE NOT IN ('Maharashtra');

 -- 5 --

SELECT * FROM CLIENT_MASTER WHERE CLIENTNO='C00001';

-- 6 --
UPDATE PRODUCT_MASTER SET SELLPRICE=1150.50 WHERE UNITMEASURE='1.44 drive';

-- 7 --
DELETE FROM CLIENT_MASTER WHERE CLIENTNO='C00005';

-- 8 --
SELECT NAME FROM CLIENT_MASTER WHERE CITY LIKE '_a%';

-- 9 --
SELECT COUNT(DESCRIPTION) FROM PRODUCT_MASTER WHERE (SELLPRICE >= 1500);

-- 10 --
SELECT QTYORDERED, QTYDISP FROM SALES_ORDER_DETAILS;


---- COMMANDS -----
-- 1 --
ALTER TABLE CLIENT_MASTER ADD PRIMARY KEY(CLIENTNO);

-- 2 --
ALTER TABLE CLIENT_MASTER ADD PHONE_NO NUMERIC(10);
SELECT * FROM CLIENT_MASTER;

-- 3 --
ALTER TABLE PRODUCT_MASTER ALTER COLUMN DESCRIPTION VARCHAR(15) NOT NULL;
ALTER TABLE PRODUCT_MASTER ALTER COLUMN PROFITPERC NUMERIC(4,2) NOT NULL;
ALTER TABLE PRODUCT_MASTER ALTER COLUMN SELLPRICE NUMERIC(8,2) NOT NULL;
ALTER TABLE PRODUCT_MASTER ALTER COLUMN COSTPRICE NUMERIC(8,2) NOT NULL;

-- 4 --
ALTER TABLE CLIENT_MASTER ALTER COLUMN NAME VARCHAR(60);

-- 5 --
--ALTER TABLE CLIENT_MASTER DROP COLUMN PINCODE;


-- JOINS --
-- 1 --
SELECT pm.PRODUCTNO, pm.DESCRIPTION
FROM CLIENT_MASTER cm
JOIN SALES_ORDER so ON so.CLIENTNO = cm.CLIENTNO
JOIN SALES_ORDER_DETAILS sod ON sod.ORDERNO = so.ORDERNO
JOIN PRODUCT_MASTER pm ON pm.PRODUCTNO = sod.PRODUCTNO
WHERE cm.NAME = 'Ivan Bayross';

-- 2 --
SELECT sod.PRODUCTNO, pm.DESCRIPTION, sod.QTYDISP
FROM SALES_ORDER so
JOIN SALES_ORDER_DETAILS sod ON sod.ORDERNO = so.ORDERNO
JOIN PRODUCT_MASTER pm ON pm.PRODUCTNO = sod.PRODUCTNO
WHERE MONTH(so.DELYDATE) = MONTH(GETDATE()) AND YEAR(so.DELYDATE) = YEAR(GETDATE());

-- 3 --
SELECT sod.PRODUCTNO, pm.DESCRIPTION
FROM SALES_ORDER_DETAILS sod
JOIN PRODUCT_MASTER pm ON pm.PRODUCTNO = sod.PRODUCTNO
GROUP BY sod.PRODUCTNO, pm.DESCRIPTION
HAVING SUM(sod.QTYDISP) >= 100;

-- 4 --
SELECT cm.NAME
FROM CLIENT_MASTER cm
JOIN SALES_ORDER so ON so.CLIENTNO = cm.CLIENTNO
JOIN SALES_ORDER_DETAILS sod ON sod.ORDERNO = so.ORDERNO
JOIN PRODUCT_MASTER pm ON pm.PRODUCTNO = sod.PRODUCTNO
WHERE pm.DESCRIPTION = 'Trousers';

-- 5 --
SELECT sod.PRODUCTNO, pm.DESCRIPTION, so.ORDERNO, so.ORDERDATE
FROM CLIENT_MASTER cm
JOIN SALES_ORDER so ON so.CLIENTNO = cm.CLIENTNO
JOIN SALES_ORDER_DETAILS sod ON sod.ORDERNO = so.ORDERNO
JOIN PRODUCT_MASTER pm ON pm.PRODUCTNO = sod.PRODUCTNO
WHERE pm.DESCRIPTION = 'Pull Overs' AND sod.QTYORDERED < 5;

-- SUBQUERIES --
-- 1 --
SELECT PM.*
FROM PRODUCT_MASTER PM
LEFT JOIN SALES_ORDER_DETAILS SOD ON PM.PRODUCTNO = SOD.PRODUCTNO
WHERE SOD.PRODUCTNO IS NULL;

-- 2 --
SELECT CM.NAME, CM.ADDRESS1, CM.ADDRESS2, CM.CITY, CM.STATE
FROM CLIENT_MASTER CM
JOIN SALES_ORDER SO ON CM.CLIENTNO = SO.CLIENTNO
WHERE SO.ORDERNO = '019001';

-- 3 --
SELECT DISTINCT CM.*
FROM CLIENT_MASTER CM
JOIN SALES_ORDER SO ON CM.CLIENTNO = SO.CLIENTNO
WHERE SO.ORDERDATE < '2002-05-01';



-- 1 --
SELECT DATENAME(weekday,'2012-02-11')+','+
DATENAME(MONTH,'2012-02-11')+''+
CAST(DATEPART(day,'2012-02-11') AS VARCHAR(2))+','+
CAST (DATEPART(year,'2012-02-11') as varchar(4))AS SYSTEM_DATE;

-- 2 --
SELECT BALDUE from CLIENT_MASTER WHERE BALDUE =$99999.99;

-- 3 --
SELECT 'Salesman Aman sold goods of 50 while given target was 100' AS message;

-- 4 --
SELECT DATEDIFF(year,'1998-04-16',GETDATE()) AS age_in_years;




